### ISSUE TITLE
Meteor/bable

### ISSUE THREAD

**Issue by morbidpete** [aptalca/docker-plexrequests#12]
after updating the docker using Unraids GUI I stared receiving this error on the webpage

```
`/config/plexrequests-meteor/.meteor/local/build/programs/server/boot.js:348
}).run();
   ^

Error: The babel-runtime npm package could not be found in your node_modules 
directory. Please run the following command to install it:

  meteor npm install --save babel-runtime

    at meteorInstall.node_modules.meteor.babel-runtime.babel-runtime.js (packages/babel-runtime.js:37:9)
    at fileEvaluate (packages/modules-runtime.js:181:9)
    at require (packages/modules-runtime.js:106:16)
    at packages/babel-runtime.js:139:15
    at packages/babel-runtime.js:150:3
    at /config/plexrequests-meteor/.meteor/local/build/programs/server/boot.js:295:34
    at Array.forEach (native)
    at Function._.each._.forEach (/home/.meteor/packages/meteor-tool/.1.4.2_1.r4gde0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
    at /config/plexrequests-meteor/.meteor/local/build/programs/server/boot.js:128:5
    at /config/plexrequests-meteor/.meteor/local/build/programs/server/boot.js:344:5
Exited with code: 1
Your application is crashing. Waiting for file change.`
```

If I run that command using docker exec it downloads and the rror goes away but I just get a blank screen with the usual background color. Here is the log for the docker also from startup

```
`*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/firstrun.sh...
<-------------------------------------->

<-------------------------------------->
Starting container on Wed Nov 16 17:52:47 EST 2016
First install detected, cloning repository
Cloning into 'plexrequests-meteor'...
Selecting the desired branch
Using the master branch
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Fixing permissions
Updating meteor. . . may take a while if meteor servers are being slow. The web gui will not go up until update is completed and there will be another message about PlexRquests starting
nobody, this is your first time using Meteor!
Installing a Meteor distribution in your home directory.
npm-container: updating npm dependencies -- winston...

Changes to your project's package version selections from updating the release:


accounts-base upgraded from 1.2.2 to 1.2.14
accounts-password upgraded from 1.1.4 to 1.3.2
allow-deny added, version 1.0.5

autoupdate upgraded from 1.2.4 to 1.2.8
babel-compiler* upgraded from 5.8.24_1 to 6.13.0
babel-runtime upgraded from 0.1.4 to 0.1.12
base64 upgraded from 1.0.4 to 1.0.10
binary-heap upgraded from 1.0.4 to 1.0.10
blaze upgraded from 2.1.3 to 2.1.8
blaze-tools upgraded from 1.0.4 to 1.0.9
boilerplate-generator upgraded from 1.0.4 to 1.0.11
caching-compiler upgraded from 1.0.0 to 1.0.4
caching-html-compiler upgraded from 1.0.2 to 1.0.6
callback-hook upgraded from 1.0.4 to 1.0.10
check upgraded from 1.1.0 to 1.2.4
ddp upgraded from 1.2.2 to 1.2.5
ddp-client upgraded from 1.2.1 to 1.2.5
ddp-common upgraded from 1.2.2 to 1.2.5
ddp-rate-limiter upgraded from 1.0.0 to 1.0.6
ddp-server upgraded from 1.2.2 to 1.2.6
deps upgraded from 1.0.9 to 1.0.12
diff-sequence upgraded from 1.0.1 to 1.0.7
ecmascript upgraded from 0.1.6 to 0.5.9
ecmascript-runtime upgraded from 0.2.6 to 0.3.15
ejson upgraded from 1.0.7 to 1.0.13
email upgraded from 1.0.8 to 1.1.18
fastclick upgraded from 1.0.7 to 1.0.11
geojson-utils upgraded from 1.0.4 to 1.0.10
hot-code-push upgraded from 1.0.0 to 1.0.4
html-tools upgraded from 1.0.5 to 1.0.10
htmljs upgraded from 1.0.5 to 1.0.10
http upgraded from 1.1.1 to 1.2.10
id-map upgraded from 1.0.4 to 1.0.9
jquery upgraded from 1.11.4 to 1.11.10
launch-screen upgraded from 1.0.4 to 1.0.11
livedata upgraded from 1.0.15 to 1.0.18
localstorage upgraded from 1.0.5 to 1.0.12
logging upgraded from 1.0.8 to 1.1.16
meteor upgraded from 1.1.10 to 1.6.0
meteor-base upgraded from 1.0.1 to 1.0.4
minifier-css added, version 1.1.13

minifier-js added, version 1.1.13

minifiers removed from your project
minimongo upgraded from 1.0.10 to 1.0.18
mobile-experience upgraded from 1.0.1 to 1.0.4
mobile-status-bar upgraded from 1.0.6 to 1.0.12
modules added, version 0.7.7

modules-runtime added, version 0.7.7

mongo upgraded from 1.1.3 to 1.1.14
mongo-id upgraded from 1.0.1 to 1.0.6
npm-bcrypt upgraded from 0.7.8_2 to 0.9.2
npm-mongo* upgraded from 1.4.39_1 to 2.2.11_2
observe-sequence upgraded from 1.0.7 to 1.0.12
ordered-dict upgraded from 1.0.4 to 1.0.9
promise upgraded from 0.5.1 to 0.8.8
random upgraded from 1.0.5 to 1.0.10
rate-limit upgraded from 1.0.0 to 1.0.6
reactive-dict upgraded from 1.1.3 to 1.1.8
reactive-var upgraded from 1.0.6 to 1.0.11
reload upgraded from 1.1.4 to 1.1.11
retry upgraded from 1.0.4 to 1.0.7
routepolicy upgraded from 1.0.6 to 1.0.12
service-configuration upgraded from 1.0.5 to 1.0.11
session upgraded from 1.1.1 to 1.1.7
sha upgraded from 1.0.4 to 1.0.9
spacebars upgraded from 1.0.7 to 1.0.12
spacebars-compiler upgraded from 1.0.7 to 1.0.12
srp upgraded from 1.0.4 to 1.0.10
standard-minifier-css added, version 1.0.8

standard-minifier-js added, version 1.0.8

standard-minifiers upgraded from 1.0.2 to 1.0.6
templating upgraded from 1.1.5 to 1.1.9
templating-tools upgraded from 1.0.0 to 1.0.4
tracker upgraded from 1.0.9 to 1.1.1
ui upgraded from 1.0.8 to 1.0.11
underscore upgraded from 1.0.4 to 1.0.10
url upgraded from 1.0.5 to 1.0.11
webapp upgraded from 1.2.3 to 1.3.12
webapp-hashing upgraded from 1.0.5 to 1.0.9


* These packages have been updated to new versions that are not backwards
compatible.
plexrequests-meteor: updated to Meteor 1.4.2.1.

Changes to your project's package version selections from updating package


:

accounts-password upgraded from 1.3.2 to 1.3.3
alanning:roles upgraded from 1.2.14 to 1.2.15
aldeed:autoform upgraded from 5.7.1 to 5.8.1
aldeed:collection2 upgraded from 2.5.0 to 2.10.0
aldeed:collection2-core added, version 1.2.0

aldeed:schema-deny added, version 1.1.0

aldeed:schema-index added, version 1.1.1

aldeed:simple-schema upgraded from 1.3.3 to 1.5.3
aslagle:reactive-table upgraded from 0.8.18 to 0.8.38
autoupdate upgraded from 1.2.8 to 1.2.11
babel-runtime* upgraded from 0.1.12 to 1.0.1
blaze upgraded from 2.1.8 to 2.1.9
blaze-html-templates upgraded from 1.0.1 to 1.0.5
blaze-tools upgraded from 1.0.9 to 1.0.10
caching-compiler upgraded from 1.0.4 to 1.1.9
caching-html-compiler upgraded from 1.0.6 to 1.0.7
coffeescript upgraded from 1.0.11 to 1.0.17
dburles:collection-helpers upgraded from 1.0.4 to 1.1.0
ddp-client upgraded from 1.2.5 to 1.2.9
ddp-common upgraded from 1.2.5 to 1.2.8
ddp-server upgraded from 1.2.6 to 1.2.10
ecmascript upgraded from 0.5.9 to 0.6.1
fastclick upgraded from 1.0.11 to 1.0.13
fortawesome:fontawesome upgraded from 4.4.0 to 4.7.0
fourseven:scss upgraded from 3.4.1 to 3.10.1
html-tools upgraded from 1.0.10 to 1.0.11
htmljs upgraded from 1.0.10 to 1.0.11
iron:router upgraded from 1.0.12 to 1.0.13
launch-screen upgraded from 1.0.11 to 1.0.12
less upgraded from 2.5.1 to 2.5.7
mdg:validation-error added, version 0.2.0

minifier-css upgraded from 1.1.13 to 1.2.15
minifier-js upgraded from 1.1.13 to 1.2.15
minimongo upgraded from 1.0.18 to 1.0.19
mobile-status-bar upgraded from 1.0.12 to 1.0.13
momentjs:moment upgraded from 2.10.6 to 2.16.0
observe-sequence upgraded from 1.0.12 to 1.0.14
percolate:synced-cron upgraded from 1.3.0 to 1.3.2
raix:eventemitter added, version 0.1.3

retry upgraded from 1.0.7 to 1.0.9
shell-server added, version 0.2.1

softwarerero:accounts-t9n upgraded from 1.1.6 to 1.3.5
spacebars upgraded from 1.0.12 to 1.0.13
spacebars-compiler upgraded from 1.0.12 to 1.0.13
standard-minifier-css upgraded from 1.0.8 to 1.3.2
standard-minifier-js upgraded from 1.0.8 to 1.2.1
standard-minifiers removed from your project
templating upgraded from 1.1.9 to 1.2.15
templating-compiler added, version 1.2.15

templating-runtime added, version 1.2.15

templating-tools upgraded from 1.0.4 to 1.0.5
themeteorchef:bert upgraded from 2.1.0 to 2.1.1
ui upgraded from 1.0.11 to 1.0.12
useraccounts:bootstrap upgraded from 1.12.4 to 1.14.2
useraccounts:core upgraded from 1.12.4 to 1.14.2


* These packages have been updated to new versions that are not backwards
compatible.

The following top-level dependencies were not updated to the very latest
version available:

* ongoworks:security 1.3.0 (2.0.1 is available)
* twbs:bootstrap 4.0.0-alpha (4.0.0-alpha2 is available)

Newer versions of the following indirect dependencies are available:
* autoupdate 1.2.11 (1.3.12 is available)
* blaze 2.1.9 (2.2.0 is available)
* coffeescript 1.0.17 (1.11.1_4 is available)
* ddp-client 1.2.9 (1.3.2 is available)
* ddp-server 1.2.10 (1.3.12 is available)
* launch-screen 1.0.12 (1.1.0 is available)
* less 2.5.7 (2.7.8 is available)
* mdg:validation-error 0.2.0 (0.5.1 is available)

To update one or more of these packages, pass their names to
`meteor update`, or just run `meteor update --all-packages`.
Starting PlexRequests. The web gui will be up once the message 'App running at: http://localhost' is displayed
*** Running /etc/rc.local...
*** Booting runit daemon...
*** Runit started as PID 514
Nov 16 17:54:37 9766e488128f syslog-ng[523]: syslog-ng starting up; version='3.5.3'

[[[[[ /config/plexrequests-meteor ]]]]]

=> Started proxy.
[[[[[ /config/plexrequests-meteor ]]]]]

=> Started proxy.
=> Started MongoDB.
[34mW20161116-17:55:06.076(-5)? (STDERR) [39m[35m/config/plexrequests-meteor/.meteor/local/build/programs/server/boot.js:348[39m
[34mW20161116-17:55:06.107(-5)? (STDERR) [39m[35m}).run();[39m
[34mW20161116-17:55:06.107(-5)? (STDERR) [39m[35m ^[39m
[34mW20161116-17:55:06.107(-5)? (STDERR) [39m[35m[39m
[34mW20161116-17:55:06.107(-5)? (STDERR) [39m[35mError: The babel-runtime npm package could not be found in your node_modules [39m
[34mW20161116-17:55:06.108(-5)? (STDERR) [39m[35mdirectory. Please run the following command to install it:[39m
[34mW20161116-17:55:06.108(-5)? (STDERR) [39m[35m[39m
[34mW20161116-17:55:06.108(-5)? (STDERR) [39m[35m meteor npm install --save babel-runtime[39m
[34mW20161116-17:55:06.108(-5)? (STDERR) [39m[35m[39m
[34mW20161116-17:55:06.108(-5)? (STDERR) [39m[35m at meteorInstall.node_modules.meteor.babel-runtime.babel-runtime.js (packages/babel-runtime.js:37:9)[39m
[34mW20161116-17:55:06.109(-5)? (STDERR) [39m[35m at fileEvaluate (packages/modules-runtime.js:181:9)[39m
[34mW20161116-17:55:06.109(-5)? (STDERR) [39m[35m at require (packages/modules-runtime.js:106:16)[39m
[34mW20161116-17:55:06.109(-5)? (STDERR) [39m[35m at packages/babel-runtime.js:139:15[39m
[34mW20161116-17:55:06.109(-5)? (STDERR) [39m[35m at packages/babel-runtime.js:150:3[39m
[34mW20161116-17:55:06.109(-5)? (STDERR) [39m[35m at /config/plexrequests-meteor/.meteor/local/build/programs/server/boot.js:295:34[39m
[34mW20161116-17:55:06.109(-5)? (STDERR) [39m[35m at Array.forEach (native)[39m
[34mW20161116-17:55:06.109(-5)? (STDERR) [39m[35m at Function._.each._.forEach (/home/.meteor/packages/meteor-tool/.1.4.2_1.r4gde0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)[39m
[34mW20161116-17:55:06.110(-5)? (STDERR) [39m[35m at /config/plexrequests-meteor/.meteor/local/build/programs/server/boot.js:128:5[39m
[34mW20161116-17:55:06.110(-5)? (STDERR) [39m[35m at /config/plexrequests-meteor/.meteor/local/build/programs/server/boot.js:344:5[39m
=> Exited with code: 1
[34mW20161116-17:55:06.878(-5)? (STDERR) [39m[35m/config/plexrequests-meteor/.meteor/local/build/programs/server/boot.js:348[39m
[34mW20161116-17:55:06.879(-5)? (STDERR) [39m[35m}).run();[39m
[34mW20161116-17:55:06.879(-5)? (STDERR) [39m[35m ^[39m
[34mW20161116-17:55:06.879(-5)? (STDERR) [39m[35m[39m
[34mW20161116-17:55:06.880(-5)? (STDERR) [39m[35mError: The babel-runtime npm package could not be found in your node_modules [39m
[34mW20161116-17:55:06.880(-5)? (STDERR) [39m[35mdirectory. Please run the following command to install it:[39m
[34mW20161116-17:55:06.880(-5)? (STDERR) [39m[35m[39m
[34mW20161116-17:55:06.880(-5)? (STDERR) [39m[35m meteor npm install --save babel-runtime[39m
[34mW20161116-17:55:06.880(-5)? (STDERR) [39m[35m[39m
[34mW20161116-17:55:06.880(-5)? (STDERR) [39m[35m at meteorInstall.node_modules.meteor.babel-runtime.babel-runtime.js (packages/babel-runtime.js:37:9)[39m
[34mW20161116-17:55:06.881(-5)? (STDERR) [39m[35m at fileEvaluate (packages/modules-runtime.js:181:9)[39m
[34mW20161116-17:55:06.881(-5)? (STDERR) [39m[35m at require (packages/modules-runtime.js:106:16)[39m
[34mW20161116-17:55:06.881(-5)? (STDERR) [39m[35m at packages/babel-runtime.js:139:15[39m
[34mW20161116-17:55:06.881(-5)? (STDERR) [39m[35m at packages/babel-runtime.js:150:3[39m
[34mW20161116-17:55:06.881(-5)? (STDERR) [39m[35m at /config/plexrequests-meteor/.meteor/local/build/programs/server/boot.js:295:34[39m
[34mW20161116-17:55:06.881(-5)? (STDERR) [39m[35m at Array.forEach (native)[39m
[34mW20161116-17:55:06.881(-5)? (STDERR) [39m[35m at Function._.each._.forEach (/home/.meteor/packages/meteor-tool/.1.4.2_1.r4gde0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)[39m
[34mW20161116-17:55:06.881(-5)? (STDERR) [39m[35m at /config/plexrequests-meteor/.meteor/local/build/programs/server/boot.js:128:5[39m
[34mW20161116-17:55:06.884(-5)? (STDERR) [39m[35m at /config/plexrequests-meteor/.meteor/local/build/programs/server/boot.js:344:5[39m
=> Exited with code: 1
[34mW20161116-17:55:07.582(-5)? (STDERR) [39m[35m/config/plexrequests-meteor/.meteor/local/build/programs/server/boot.js:348[39m
[34mW20161116-17:55:07.582(-5)? (STDERR) [39m[35m}).run();[39m
[34mW20161116-17:55:07.582(-5)? (STDERR) [39m[35m ^[39m
[34mW20161116-17:55:07.583(-5)? (STDERR) [39m[35m[39m
[34mW20161116-17:55:07.583(-5)? (STDERR) [39m[35mError: The babel-runtime npm package could not be found in your node_modules [39m
[34mW20161116-17:55:07.583(-5)? (STDERR) [39m[35mdirectory. Please run the following command to install it:[39m
[34mW20161116-17:55:07.583(-5)? (STDERR) [39m[35m[39m
[34mW20161116-17:55:07.583(-5)? (STDERR) [39m[35m meteor npm install --save babel-runtime[39m
[34mW20161116-17:55:07.583(-5)? (STDERR) [39m[35m[39m
[34mW20161116-17:55:07.583(-5)? (STDERR) [39m[35m at meteorInstall.node_modules.meteor.babel-runtime.babel-runtime.js (packages/babel-runtime.js:37:9)[39m
[34mW20161116-17:55:07.584(-5)? (STDERR) [39m[35m at fileEvaluate (packages/modules-runtime.js:181:9)[39m
[34mW20161116-17:55:07.584(-5)? (STDERR) [39m[35m at require (packages/modules-runtime.js:106:16)[39m
[34mW20161116-17:55:07.584(-5)? (STDERR) [39m[35m at packages/babel-runtime.js:139:15[39m
[34mW20161116-17:55:07.584(-5)? (STDERR) [39m[35m at packages/babel-runtime.js:150:3[39m
[34mW20161116-17:55:07.584(-5)? (STDERR) [39m[35m at /config/plexrequests-meteor/.meteor/local/build/programs/server/boot.js:295:34[39m
[34mW20161116-17:55:07.584(-5)? (STDERR) [39m[35m at Array.forEach (native)[39m
[34mW20161116-17:55:07.584(-5)? (STDERR) [39m[35m at Function._.each._.forEach (/home/.meteor/packages/meteor-tool/.1.4.2_1.r4gde0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)[39m
[34mW20161116-17:55:07.585(-5)? (STDERR) [39m[35m at /config/plexrequests-meteor/.meteor/local/build/programs/server/boot.js:128:5[39m
[34mW20161116-17:55:07.586(-5)? (STDERR) [39m[35m at /config/plexrequests-meteor/.meteor/local/build/programs/server/boot.js:344:5[39m
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
[34mW20161116-17:55:07.582(-5)? (STDERR) [39m[35m/config/plexrequests-meteor/.meteor/local/build/programs/server/boot.js:348[39m
[34mW20161116-17:55:07.582(-5)? (STDERR) [39m[35m}).run();[39m
[34mW20161116-17:55:07.582(-5)? (STDERR) [39m[35m ^[39m
[34mW20161116-17:55:07.583(-5)? (STDERR) [39m[35m[39m
[34mW20161116-17:55:07.583(-5)? (STDERR) [39m[35mError: The babel-runtime npm package could not be found in your node_modules [39m
[34mW20161116-17:55:07.583(-5)? (STDERR) [39m[35mdirectory. Please run the following command to install it:[39m
[34mW20161116-17:55:07.583(-5)? (STDERR) [39m[35m[39m
[34mW20161116-17:55:07.583(-5)? (STDERR) [39m[35m meteor npm install --save babel-runtime[39m
[34mW20161116-17:55:07.583(-5)? (STDERR) [39m[35m[39m
[34mW20161116-17:55:07.583(-5)? (STDERR) [39m[35m at meteorInstall.node_modules.meteor.babel-runtime.babel-runtime.js (packages/babel-runtime.js:37:9)[39m
[34mW20161116-17:55:07.584(-5)? (STDERR) [39m[35m at fileEvaluate (packages/modules-runtime.js:181:9)[39m
[34mW20161116-17:55:07.584(-5)? (STDERR) [39m[35m at require (packages/modules-runtime.js:106:16)[39m
[34mW20161116-17:55:07.584(-5)? (STDERR) [39m[35m at packages/babel-runtime.js:139:15[39m
[34mW20161116-17:55:07.584(-5)? (STDERR) [39m[35m at packages/babel-runtime.js:150:3[39m
[34mW20161116-17:55:07.584(-5)? (STDERR) [39m[35m at /config/plexrequests-meteor/.meteor/local/build/programs/server/boot.js:295:34[39m
[34mW20161116-17:55:07.584(-5)? (STDERR) [39m[35m at Array.forEach (native)[39m
[34mW20161116-17:55:07.584(-5)? (STDERR) [39m[35m at Function._.each._.forEach (/home/.meteor/packages/meteor-tool/.1.4.2_1.r4gde0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)[39m
[34mW20161116-17:55:07.585(-5)? (STDERR) [39m[35m at /config/plexrequests-meteor/.meteor/local/build/programs/server/boot.js:128:5[39m
[34mW20161116-17:55:07.586(-5)? (STDERR) [39m[35m at /config/plexrequests-meteor/.meteor/local/build/programs/server/boot.js:344:5[39m
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.`
```
unraid 6.3.0-rc4

**Comment by aptalca** [comment]
It seems the latest meteor update broke it. I'm looking into it.

**Comment by morbidpete** [comment]
No rush. Appreciate it

**Comment by aaomidi** [comment]
Hey! Thanks for maintaining this. Any updates?

**Comment by thejkayway** [comment]
I've been poking around a bit but if anyone is in a hurry to get back up and running you can just build your own image after replacing line 33 of startup.sh with "/sbin/setuser nobody meteor update --release 1.3.5.1"

Gets it working but it's pretty hacky

**Comment by aaomidi** [comment]
@bellyjeans55 If that solves it, why not do a PR? :3
